/**
 * dataintegrationapi
 * Easily and directly query database backup files, convert into other file formats.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MssqlBakEnumerateTablesResult', 'model/MssqlTable', 'api/BackupConvertApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/MssqlBakEnumerateTablesResult'), require('./model/MssqlTable'), require('./api/BackupConvertApi'));
  }
}(function(ApiClient, MssqlBakEnumerateTablesResult, MssqlTable, BackupConvertApi) {
  'use strict';

  /**
   * Easily_and_directly_query_database_backup_files_convert_into_other_file_formats_.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var CloudmersiveDataintegrationApiClient = require('index'); // See note below*.
   * var xxxSvc = new CloudmersiveDataintegrationApiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new CloudmersiveDataintegrationApiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new CloudmersiveDataintegrationApiClient.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new CloudmersiveDataintegrationApiClient.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 2.0.3
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The MssqlBakEnumerateTablesResult model constructor.
     * @property {module:model/MssqlBakEnumerateTablesResult}
     */
    MssqlBakEnumerateTablesResult: MssqlBakEnumerateTablesResult,
    /**
     * The MssqlTable model constructor.
     * @property {module:model/MssqlTable}
     */
    MssqlTable: MssqlTable,
    /**
     * The BackupConvertApi service constructor.
     * @property {module:api/BackupConvertApi}
     */
    BackupConvertApi: BackupConvertApi
  };

  return exports;
}));
