/**
 * Data Integration API
 * Easily and directly query database backup files, convert into other file formats.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CloudmersiveDataintegrationApiClient);
  }
}(this, function(expect, CloudmersiveDataintegrationApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CloudmersiveDataintegrationApiClient.MssqlBakEnumerateTablesResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MssqlBakEnumerateTablesResult', function() {
    it('should create an instance of MssqlBakEnumerateTablesResult', function() {
      // uncomment below and update the code to test MssqlBakEnumerateTablesResult
      //var instance = new CloudmersiveDataintegrationApiClient.MssqlBakEnumerateTablesResult();
      //expect(instance).to.be.a(CloudmersiveDataintegrationApiClient.MssqlBakEnumerateTablesResult);
    });

    it('should have the property successful (base name: "successful")', function() {
      // uncomment below and update the code to test the property successful
      //var instance = new CloudmersiveDataintegrationApiClient.MssqlBakEnumerateTablesResult();
      //expect(instance).to.be();
    });

    it('should have the property tables (base name: "tables")', function() {
      // uncomment below and update the code to test the property tables
      //var instance = new CloudmersiveDataintegrationApiClient.MssqlBakEnumerateTablesResult();
      //expect(instance).to.be();
    });

  });

}));
