/**
 * dataintegrationapi
 * Easily and directly query database backup files, convert into other file formats.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MssqlTable'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MssqlTable'));
  } else {
    // Browser globals (root is window)
    if (!root.CloudmersiveDataintegrationApiClient) {
      root.CloudmersiveDataintegrationApiClient = {};
    }
    root.CloudmersiveDataintegrationApiClient.MssqlBakEnumerateTablesResult = factory(root.CloudmersiveDataintegrationApiClient.ApiClient, root.CloudmersiveDataintegrationApiClient.MssqlTable);
  }
}(this, function(ApiClient, MssqlTable) {
  'use strict';




  /**
   * The MssqlBakEnumerateTablesResult model module.
   * @module model/MssqlBakEnumerateTablesResult
   * @version 2.0.2
   */

  /**
   * Constructs a new <code>MssqlBakEnumerateTablesResult</code>.
   * Result of enumeerating Tables in a SQL Server Backup (.BAK) file
   * @alias module:model/MssqlBakEnumerateTablesResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>MssqlBakEnumerateTablesResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MssqlBakEnumerateTablesResult} obj Optional instance to populate.
   * @return {module:model/MssqlBakEnumerateTablesResult} The populated <code>MssqlBakEnumerateTablesResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('successful')) {
        obj['successful'] = ApiClient.convertToType(data['successful'], 'Boolean');
      }
      if (data.hasOwnProperty('tables')) {
        obj['tables'] = ApiClient.convertToType(data['tables'], [MssqlTable]);
      }
    }
    return obj;
  }

  /**
   * True if successful, False otherwise
   * @member {Boolean} successful
   */
  exports.prototype['successful'] = undefined;
  /**
   * SQL Server Tables in the backup file
   * @member {Array.<module:model/MssqlTable>} tables
   */
  exports.prototype['tables'] = undefined;



  return exports;
}));


